server:
  port: 8089

spring:
  h2:
    console:
      enable: true
      path: /h2
    profiles:
      active: local
    datasource:
        hikari:
          jdbc-url: jdbc:h2:~/IdeaProjects/spring-boot-practice/data/wikidb.db;
          #jdbc-url: jdbc:h2:tcp//localhost:9092/./data/wikidb
          driver-clsas-name: org.h2.Driver
          username: sa
          password: apm1234

logging:
  level:
    org.hivernate.SQL: debug